name: Deploy

on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker build . -t ${{secrets.DOCKER_HUB_USERNAME}}/airtime2cash
      - run: echo "${{ secrets.DOCKER_HUB_PASSWORD}}" | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
      -run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/airtime2cash
